import { ContentBlock } from "@/app/read/page";

export const articleContent: ContentBlock[] = [
  // Prologue
  { type: "title", text: "Prologue" },
  { type: "paragraph", text: "Welcome to the inaugural issue of *The Aevum*, a journey through the ever-evolving landscape of technology and human ingenuity. Our name, derived from the Latin for 'eternity,' reflects our mission: to explore the ideas that connect yesterday’s dreams, today’s innovations, and tomorrow’s possibilities. In these pages, we delve into the Rik: the ethical dilemmas of ghostwriting, the relentless pursuit of digital control through dopamine, and the transformative potential of quantum computing, AI, robotics, and brain-computer interfaces. Each article is a spark meant to ignite curiosity and inspire action. As you turn these pages, may you find yourself at the intersection of wonder and responsibility, ready to shape a future where technology serves humanity’s highest aspirations." },
  { type: "author", text: "The NeuroNumb Team" },

  // Article 1: Ghostwriting in Technical Writing
  { type: "title", text: "Ghostwriting in Technical Writing: An Ethical Dilemma" },
  { type: "author", text: "Maliha Laheen" },
  { type: "date", text: "July 3, 2025" },
  { type: "image", src: "gw.png", caption: "The ghostwriter writing an article while being oblivious of its outcome" },
  { type: "paragraph", text: "Technical writing involves creating documents like instruction manuals, reports, and guides used in fields such as technology, medicine, or engineering. These documents must be clear and accurate. However, sometimes the person who writes them does not receive credit. This practice, known as ghostwriting, occurs when someone writes a document, but another person’s name, such as a boss or a company, appears as the author. While common, it raises questions about fairness and transparency. Should readers know who wrote the document? This article explores why ghostwriting matters and whether openness could make these documents more trustworthy." },
  { type: "heading", text: "The Ethical Core: Is Ghostwriting Dishonest?", level: 2 },
  { type: "paragraph", text: "Ghostwriting can feel misleading. If the person listed as the author did not write the document and lacks deep knowledge of the subject, problems may arise. For instance, a poorly written guide for a medical device could cause harm if it contains errors. On the other hand, ghostwriting can be practical. Companies hire skilled writers to ensure documents are clear and correct, even if the company itself is not an expert. This creates a balance between honesty and efficiency. Some argue readers should know the writer’s identity to judge the document’s reliability. Others believe the accuracy of the information is more important than who wrote it." },
  { type: "image", src: "gw2.png", caption: "A ghost written article with fake promotion and people protesting against that" },
  { type: "heading", text: "Philosophical Reflections: Who Should Get Credit?", level: 2 },
  { type: "paragraph", text: "Typically, the person who writes something is considered the author and is responsible for its content. Ghostwriting changes this dynamic. The writer remains hidden, while someone else takes credit—and responsibility if issues occur. For example, if a manual is unclear and leads to a mistake, who is at fault: the writer or the person named as the author? One perspective supports ghostwriting if it results in better documents that benefit users. However, another view considers it unfair to conceal the true writer. This raises a question: Does being an author mean doing the work, receiving recognition, or both?" },
  { type: "heading", text: "The Ghostwriter’s Challenge: Working Without Credit", level: 2 },
  { type: "paragraph", text: "Ghostwriters face a difficult task. They must write accurately and clearly while aligning with the client’s preferences, all without public recognition. This lack of credit can feel unfair—why should someone else be praised for their work? Ghostwriters also strive to maintain accuracy, sometimes disagreeing with clients to ensure correctness. Since their names are not attached, it can be hard to feel fully accountable. Revealing the writer’s role might help, but it could complicate matters or make the client appear less knowledgeable." },
  { type: "heading", text: "Case Study: When Ghostwriting Causes Problems", level: 2 },
  { type: "paragraph", text: "Consider a scenario where a ghostwriter creates a report about a new medical device, credited to a well-known doctor. If the report contains mistakes and the device fails, people may blame the doctor, who did not write it. This confusion can reduce trust in the report. Had the ghostwriter’s involvement been disclosed, readers might have reviewed it more carefully, potentially avoiding the issue. This example highlights the risks of hiding the true writer." },
  { type: "heading", text: "Guidelines for Ethical Ghostwriting", level: 2 },
  { type: "list", items: [
    "Be Honest: Whenever possible, indicate who wrote the document, even subtly.",
    "Own the Work: The credited author should review the document and ensure its accuracy.",
    "Focus on Truth: Writers should prioritize factual correctness, even if clients suggest otherwise.",
    "Give Some Credit: Acknowledge the writer’s contribution, even privately."
  ] },
  { type: "heading", text: "Conclusion: Finding the Right Way", level: 2 },
  { type: "paragraph", text: "Ghostwriting is valuable for producing clear documents but raises concerns about fairness and responsibility. Transparency about authorship might be the most honest approach, though it is not always practical. By considering both the benefits and challenges, ghostwriting can be used thoughtfully. The goal is to ensure these documents are reliable and helpful for those who depend on them." },
  { type: "image", src: "gw3.png", caption: "After the guidelines were maintained" },
  { type: "image", src: "gw4.png", caption: "People are now cheerful and the ghostwriter is happy" },

  // Article 2: No Matter How Fast You Run
  { type: "title", text: "No Matter How Fast You Run, You Can't Escape Reality" },
  { type: "author", text: "Md. Asif Khan" },
  { type: "date", text: "June 28, 2025" },
  { type: "image", src: "reverse_.png", caption: "“I am the Reverse of everything you are. The dark to your light. And I will always be faster.” — Eobard Thawne to Barry Allen" },
  { type: "heading", text: "Introduction", level: 2 },
  { type: "paragraph", text: "In Detective Comics, few rivalries are as intense as the one between **Barry Allen**, the Flash and **Eobard Thawne**, the Reverse-Flash. It is a conflict not only of just speed but also of philosophy, trauma, and time itself. Their enmity forms a cosmic ouroboros—an eternal chase where the hunter and hunted are forever in loops of fate and obsession." },
  { type: "paragraph", text: "This is more than a superhero-villain feud. It’s a story of love twisted into hatred, of admiration turned into madness, and of a hero whose very existence cursed him with his deadliest enemy." },
  { type: "heading", text: "Barry Allen: The Fastest Human Alive", level: 2 },
  { type: "paragraph", text: "Introduced in *Showcase #4* (1956), Barry Allen redefined the Golden Age Flash for the modern era. A forensic scientist gifted with super-speed via a lightning strike and chemical spill, Barry channels his trauma (notably the death of his mother and the wrongful imprisonment of his father) into a mission to protect Central City as *The Flash*." },
  { type: "heading", text: "Eobard Thawne: The Twisted Fan", level: 2 },
  { type: "paragraph", text: "Hailing from the 25th century, Eobard Thawne was once *The Flash’s biggest admirer*. He discovered the Speed Force and sought to recreate Barry’s powers. Upon doing so, he idolized the Flash—until he traveled back in time and learned his destiny: to become Barry’s greatest enemy. Thawne’s admiration became bitterness when he discovered that in his future, he was destined not to be loved like the Flash, but hated and feared. His attempts to be like Barry only isolated him further. His envy turned to wrath, and he swore not only to defeat Barry but to unravel his life, piece by piece." },
  { type: "paragraph", text: "From that realization, the *Reverse-Flash* was born not just from hate, but also from obsession. In *The Flash: Rebirth* (2009) by Geoff Johns, Thawne even creates his own **Negative Speed Force**, corrupting the very energy that empowers speedsters." },
  { type: "image", src: "vs.png", caption: "Two sides of the Speed Force: Flash and Reverse-Flash" },
  { type: "paragraph", text: "In the CW's *The Flash* television series, Thawne’s story is further expanded. After traveling back in time and being stranded in the 21st century, Thawne murders Dr. Harrison Wells and takes his identity. Under the alias of Wells, he becomes the founder of S.T.A.R. Labs and mentors Barry Allen. Using his future knowledge, he orchestrates the particle accelerator explosion, which ultimately gives Barry his powers. Ironically, the man who would become the Flash is created by his own worst enemy." },
  { type: "heading", text: "Time’s Cruel Loop: Their Twisted Conflict", level: 2 },
  { type: "paragraph", text: "The defining moment of their rivalry occurs in *The Flash (Vol. 2) #197* and *Flashpoint* (2011): **Thawne murders Barry’s mother**, Nora Allen, to make Barry suffer. In the aftermath, Barry’s father, **Henry Allen**, is wrongly convicted of the murder and sentenced to prison—despite his innocence. This single act not only traumatizes young Barry but also shapes his future path: he becomes a forensic scientist to uncover the truth and clear his father's name." },
  { type: "image", src: "flashmomdead.png", caption: "Nora Allen’s death: the event that turned a child into The Flash." },
  { type: "paragraph", text: "This tragedy reshapes Barry’s entire life and sets off the time-bending saga that would eventually birth the *Flashpoint* universe. In *Flashpoint*, Barry attempts to undo his mother's death, but his interference leads to a fractured, dystopian timeline. Ironically, Thawne reveals that Barry was the one who created the chaos—not him." },
  { type: "quote", text: "“Every hero needs an origin story. I just made yours the worst one imaginable.” — Eobard Thawne" },
  { type: "heading", text: "Themes: Obsession, Identity, and Destiny", level: 2 },
  { type: "quote", text: "“You know what the greatest tragedy is, Barry? It’s not that I killed your mother. It’s that you were too slow to stop me.” — Eobard Thawne, *CW's The Flash*" },
  { type: "paragraph", text: "The Flash and Reverse-Flash are two sides of the same coin. Barry represents **hope, justice, and legacy**, while Thawne stands for **vengeance, corruption, and obsession**. Their battles are more than just physical races—they are existential struggles:" },
  { type: "list", items: [
    "Free Will vs. Determinism: Barry constantly fights to change destiny, while Thawne ensures it remains a loop.",
    "Heroism vs. Narcissism: Barry sacrifices for others; Thawne is driven by ego and a need for recognition."
  ] },
  { type: "paragraph", text: "This theme of self-obsession versus self-sacrifice extends to other speedster enemies, such as **Savitar**. In both the comics and the CW series, Savitar is portrayed as a distorted, godlike speedster obsessed with power and control. In the show, Savitar is revealed to be a time remnant of Barry Allen himself—a future version consumed by pain and rejection, turned villainous in a desperate bid for relevance. Savitar adds another layer to the Flash's struggles: sometimes the darkest enemy is the one created by your own mistakes." },
  { type: "heading", text: "The Impact on the DC Universe", level: 2 },
  { type: "paragraph", text: "In *Flashpoint*, Thawne’s manipulation reshapes the entire DC Universe, leading to the *New 52* reboot. Thawne’s hatred is so profound that he returns from death repeatedly—through time manipulation, clones, Speed Force resurrection, and paradoxes." },
  { type: "heading", text: "The Paradox of Hate", level: 2 },
  { type: "quote", text: "“You created me, Barry. Just like I created you. We’re echoes in a loop we can never outrun.” — Eobard Thawne" },
  { type: "paragraph", text: "The ultimate irony? **Thawne only exists because of Barry Allen.** Without the Flash, there is no Reverse-Flash. But without the trauma Thawne caused, Barry wouldn’t become the man he is. It’s a loop. A tragic, cruel loop. And no matter how many timelines Barry tries to fix, Thawne always finds a way to return—faster, meaner, more obsessed." },
  { type: "heading", text: "Conclusion: No Finish Line", level: 2 },
  { type: "quote", text: "“The truth is, we are forever bound—past and future, hate and hope.” — Barry Allen, *The Flash (Vol. 3) #9*" },
  { type: "paragraph", text: "The war between Flash and Reverse-Flash isn’t just a superhero clash—it’s a metaphor. For how our past shapes us. For how light attracts darkness. And for how even the fastest man alive can’t outrun the scars of destiny. In the end, the chase continues. Not just in comics—but in the very heartbeat of DC’s legacy." },

  // Article 3: Beyond the Firewall
  { type: "title", text: "Beyond the Firewall, Threats Never Sleep" },
  { type: "author", text: "Ferdous Ara Fahima" },
  { type: "date", text: "June 28, 2025" },
  { type: "quote", text: "“There are two types of companies: those that have been hacked, and those who don’t know they have been hacked.” — John Chambers" },
  { type: "paragraph", text: "In an era where our lives are intertwined with technology, cybersecurity stands as the guardian of our digital existence. From personal data to critical infrastructure, the invisible threats lurking in the shadows of the internet are ever-present. Hackers, like skilled predators, exploit the smallest vulnerabilities, turning our reliance on technology into a potential weakness. This article explores the critical landscape of cybersecurity: its necessity, the impact of cyberattacks, and how to protect our digital future." },
  { type: "image", src: "phishing.png", caption: "Hacker is fishing. Don't be his Hilsha." },
  { type: "heading", text: "The Digital World: Scale and Stakes", level: 2 },
  { type: "paragraph", text: "As of 2025, the global population is around 8.2 billion, with 5.4 billion (66%) actively using the internet. This massive connectivity fuels innovation but also creates a vast playground for cybercriminals. Every connected device—from smartphones to IoT appliances—is a potential entry point for attacks. A single breach can lead to identity theft, financial loss, or life-threatening disruptions, making cybersecurity an urgent global priority." },
  { type: "image", src: "world.png", caption: "The world is connected, but so are the risks." },
  { type: "heading", text: "A Light Moment in the Dark Web", level: 2 },
  { type: "paragraph", text: "Why did the hacker prefer the dark web? Because the regular internet kept shedding too much light on their plans!" },
  { type: "image", src: "hacker.png", caption: "A hacker's paradise thrives in the shadows." },
  { type: "heading", text: "The Worst Cyber Attacks: A Wake-Up Call", level: 2 },
  { type: "list", items: [
    "WannaCry Ransomware (2017): Affected 200,000+ systems in 150 countries, including the UK’s NHS. Losses reached £92 million.",
    "NotPetya (2017): Spread from Ukraine to 60+ countries. Caused $10 billion in damages, hitting global giants like Maersk and FedEx.",
    "Colonial Pipeline (2021): Shut down a major US oil pipeline, causing fuel shortages and a $4.4 million ransom."
  ] },
  { type: "image", src: "city.png", caption: "The ripple effects of a cyberattack can paralyze entire systems." },
  { type: "heading", text: "Vulnerabilities: The Inevitable Weakness", level: 2 },
  { type: "paragraph", text: "If there's a vulnerability, it will be exploited. In 2024 alone, 30,000 new vulnerabilities were logged—half high or critical. From unpatched software to weak passwords, cybercriminals exploit them ruthlessly." },
  { type: "quote", text: "“Trust is the ultimate vulnerability in cybersecurity.” — Wendy Nather" },
  { type: "paragraph", text: "Defense must be proactive. A single misconfigured server or phishing email can compromise entire systems." },
  { type: "heading", text: "What We Must Do", level: 2 },
  { type: "list", items: [
    "Education: 95% of breaches come from human error.",
    "Zero-trust security: Never assume access is safe.",
    "AI-driven defenses: Can reduce breach costs by millions.",
    "Personal hygiene: Strong passwords, MFA, and software updates."
  ] },
  { type: "quote", text: "“There's no silver bullet solution with cybersecurity, a layered defense is the only viable defense.” — James Scott" },
  { type: "image", src: "security.png", caption: "Comprehensive Cyber Defense Strategy." },
  { type: "heading", text: "The Future of Earth’s Digital Landscape", level: 2 },
  { type: "paragraph", text: "Looking ahead, IoT growth (64B devices by 2026) will increase the attack surface. AI-powered attacks will exploit deepfakes and psychology. But quantum-safe encryption and real-time threat detection may level the field. Still, humans remain the weakest link. Without international cooperation and regulation, cybercrime costs (projected at $10.5 trillion in 2025) could rise further." },
  { type: "heading", text: "Sentinel’s Resolve: A Call to Action", level: 2 },
  { type: "paragraph", text: "In this digital maze, cybersecurity is not a luxury—it’s a necessity. Let’s embrace education, adopt proactive strategies, and foster global cooperation." },
  { type: "quote", text: "“Cybersecurity is a continuous cycle of protection, detection, response, and recovery.” — Chris Painter" },

  // Article 4: Quantum Computing
  { type: "title", text: "Quantum Computing: Unlocking the Future of Computation" },
  { type: "author", text: "Sultana Akter" },
  { type: "date", text: "July 3, 2025" },
  { type: "image", src: "QC-1.png", caption: "" },
  { type: "paragraph", text: "Imagine a computer solving problems in seconds that would take today's supercomputers billions of years. Quantum computing redefines computation, using qubits that exist in multiple states simultaneously. This technology could crack encryption, transform industries, or reshape society. In Bangladesh, North South University (NSU) drives regional innovation through its quantum computing lab. This article explores quantum principles, hardware, calculations, applications, and challenges in 2025." },
  { type: "heading", text: "The Pillars of Quantum Computing", level: 2 },
  { type: "paragraph", text: "Building a quantum computer is complex and revolutionary. Qubits use superposition to represent 0 and 1 simultaneously. Entanglement correlates qubits for synchronized calculations. Quantum gates enable complex, parallel operations. Quantum algorithms, like Shor's or Grover's, solve practical problems. These principles, with specialized hardware, make quantum computing transformative." },
  { type: "heading", text: "Quantum Hardware: The Engine of the Future", level: 2 },
  { type: "paragraph", text: "Quantum computers rely on advanced hardware. Quantum processors use superconducting circuits or trapped ions, operating at 15 millikelvin in dilution refrigerators. In 2025, processors integrate thousands of qubits with error correction codes like the surface code. Control systems use microwave pulses, and cryogenic systems maintain low temperatures. NSU's lab uses IBM's cloud-based processors, but scaling qubits while minimizing decoherence remains a challenge." },
  { type: "image", src: "QC-2.png", caption: "" },
  { type: "heading", text: "Quantum Calculations: Power of Quantum Mechanics", level: 2 },
  { type: "paragraph", text: "Quantum calculations leverage quantum mechanics. Qubits in Hilbert space exist in a superposition state, such as α|0⟩ + β|1⟩, where α and β are complex amplitudes. With n qubits, the system can represent 2^n states simultaneously. Quantum gates (Hadamard, CNOT) enable parallel operations. Algorithms like the Quantum Fourier Transform drive Shor's algorithm. NSU optimizes variational quantum algorithms for chemistry and cryptography, requiring precise hardware control." },
  { type: "image", src: "QC-3.jpeg", caption: "" },
  { type: "heading", text: "Quantum Applications: Transforming Industries", level: 2 },
  { type: "paragraph", text: "Quantum computing impacts multiple fields. Drug discovery uses quantum simulations for molecular modeling. Optimization benefits from quantum annealing (e.g., D-Wave). Cryptography risks Shor's algorithm but Gains from quantum key distribution. Machine learning and climate modeling improve with quantum algorithms. NSU's variational algorithms advance materials science." },
  { type: "heading", text: "Quantum Challenges: Overcoming Barriers", level: 2 },
  { type: "paragraph", text: "Quantum computing faces hurdles. Scalability is limited by decoherence, requiring ultra-cold environments. Cost of cryogenic systems limits access. Talent shortages demand physics and computer science expertise. Ethical risks include encryption threats and digital divides. NSU's education efforts help, but global collaboration is key." },
  { type: "image", src: "QC-4.jpeg", caption: "" },
  { type: "heading", text: "Why It Matters: Threat and Opportunity", level: 2 },
  { type: "paragraph", text: "Quantum computing is a double-edged sword. Shor's algorithm could break RSA encryption by 2035 (30% chance). Conversely, it offers breakthroughs in drug discovery, logistics, AI, and climate modeling. Balancing risks and opportunities is critical." },
  { type: "heading", text: "The QuantumCorp Incident: A Cautionary Tale", level: 2 },
  { type: "paragraph", text: "QuantumCorp, a fictional 2024 startup, built a quantum algorithm for financial modeling but ignored post-quantum cryptography. Hackers decrypted their cloud storage, costing $200 million. Quantum-resistant encryption could have prevented this, highlighting the need for quantum-ready security." },
  { type: "heading", text: "NSU's Quantum Leap: Regional Leadership", level: 2 },
  { type: "paragraph", text: "North South University (NSU) vista. In 2025, NSU's Quantum Computing Lab advanced variational algorithms for materials science and cryptography, using IBM's cloud processors. NSU trains students, aligning with Bangladesh's rising research output." },
  { type: "image", src: "quantumgrowth.png", caption: "Estimated quantum computing publications growth in Bangladesh (2020–2025), with contributions from NSU emphasized. Data is illustrative based on regional research patterns." },
  { type: "heading", text: "Your Quantum Strategy: Preparing for the Future", level: 2 },
  { type: "list", items: [
    "Adopt post-quantum encryption.",
    "Train employees on quantum basics.",
    "Monitor quantum breakthroughs.",
    "Test quantum algorithms in sandboxes.",
    "Partner with quantum experts.",
    "Audit cryptographic systems."
  ] },
  { type: "heading", text: "The Future of Quantum Computing", level: 2 },
  { type: "paragraph", text: "By 2030, quantum computers could scale to millions of qubits, enabling fusion energy design or global optimization. A quantum internet could ensure secure communication. Challenges like decoherence and cost persist. NSU's efforts are vital, but global collaboration ensures an inclusive quantum future." },

  // Article 5: Machine-Learned Muscles
  { type: "title", text: "Machine-Learned Muscles: Personalized Performance through AI" },
  { type: "author", text: "Tamjeed Rahman Udoy" },
  { type: "date", text: "June 28, 2025" },
  { type: "paragraph", text: "What if your body could talk—and your workout could listen? We are entering an era where our physical limitations are being challenged not just by stronger muscles or faster reflexes, but by smarter systems. The fusion of artificial intelligence (AI), biosensors, and biomechanics is giving rise to 'Machine-Learned Muscles'—a term describing adaptive, real-time systems that interpret and enhance human movement. Whether it's a runner correcting stride imbalances mid-race or a stroke survivor learning to walk again, these systems learn directly from the human body to guide smarter decisions, faster recovery, and better performance." },
  { type: "heading", text: "Core Technologies", level: 2 },
  { type: "paragraph", text: "**Wearable Sensors and Data Acquisition**  \nModern wearable devices are equipped with advanced sensors capable of measuring electrical activity in muscles (EMG), motion through accelerometers and gyroscopes, as well as pressure and torque. These sensors create a continuous flow of physiological data, turning every motion into an opportunity for learning and feedback. AI algorithms interpret this input in real time, identifying patterns that may indicate fatigue, asymmetry, or risk of injury. This granular understanding of the body's signals was previously impossible without expensive lab-based equipment." },
  { type: "paragraph", text: "**Machine Learning Models**  \nThe real power lies in AI's ability to make sense of noisy, nonlinear data. Convolutional neural networks (CNNs) help detect spatial features like muscle coordination patterns, while recurrent neural networks (RNNs) are excellent at capturing temporal dependencies—critical in movement analysis. These models can be trained on both population-wide datasets and individual user profiles to ensure both general insight and personalized accuracy. Over time, the system doesn't just monitor the body—it starts to predict how the body behaves under stress, fatigue, or in recovery." },
  { type: "image", src: "ai_sensors.png", caption: "Real-time AI feedback and correction in athletic training." },
  { type: "paragraph", text: "**Biomechanical Simulation**  \nAnother breakthrough is AI's integration with biomechanical simulation. Here, virtual musculoskeletal models mirror a user's body to simulate potential outcomes of different movements. This allows athletes to refine form in a simulated environment or therapists to test recovery plans without exposing the patient to real-world strain. These simulations can estimate joint forces, muscle tension, and range of motion, providing insights impossible to capture through surface observations alone." },
  { type: "heading", text: "Applications", level: 2 },
  { type: "paragraph", text: "**Personalized Fitness**  \nAI systems now craft highly specific workout routines based on an individual's performance, recovery patterns, and even sleep quality. For example, if an athlete shows signs of fatigue, the system may reduce reps, insert rest periods, or recommend mobility exercises. Conversely, if energy levels and movement efficiency are high, the system may increase intensity. These micro-adjustments support long-term gains while minimizing overtraining." },
  { type: "paragraph", text: "**Rehabilitation**  \nPost-injury rehabilitation is often a slow and uncertain journey. With AI, that journey becomes measurable. By tracking micro-improvements in gait, balance, and joint stability, machine-learned systems give therapists precise data to adapt treatment plans. Patients recovering from conditions like stroke, spinal cord injury, or surgery benefit from adaptive therapy that changes as they improve. This also empowers remote care, allowing patients to continue therapy at home with AI providing corrective feedback." },
  { type: "paragraph", text: "**Sports Performance Enhancement**  \nIn elite sports, every millisecond and millimeter matters. AI systems can analyze athlete movement with incredible precision, detecting subtle flaws in running, lifting, or jumping technique. They can compare an individual to biomechanical gold standards or even tailor models to an athlete's body type and sport. These insights are no longer limited to laboratories but can now be delivered on the field via mobile apps or embedded sensors." },
  { type: "image", src: "sports.jpg", caption: "AI in Sports." },
  { type: "heading", text: "Challenges and Future Directions", level: 2 },
  { type: "paragraph", text: "**Data Privacy and Ethics**  \nBiometric data, such as muscle activity and movement patterns, is sensitive. If misused, it could impact insurance, employment, or personal dignity. It is crucial that developers implement strong encryption, data anonymization, and clear user consent protocols. Federated learning offers a promising path by allowing models to be trained locally on a user's device, minimizing exposure of raw data." },
  { type: "paragraph", text: "**Model Generalization**  \nA model trained on data from young athletes may not work well for elderly patients or differently-abled individuals. To build trustworthy systems, developers must use inclusive datasets and test across diverse populations. Adaptive learning algorithms that update based on individual user behavior will be key to achieving fairness and accuracy in future applications." },
  { type: "paragraph", text: "**Integration with Robotics**  \nThe next frontier is robotics—where AI-powered exoskeletons or prosthetic limbs adapt in real time to user motion. These systems could restore mobility for millions, but they demand ultra-fast feedback loops, fail-safe mechanisms, and deep human-machine coordination. Robotics will not only assist movement but possibly enhance it, enabling tasks that were once physically impossible." },
  { type: "heading", text: "Conclusion", level: 2 },
  { type: "paragraph", text: "Machine-learned muscles are transforming the way we move, heal, and train. These intelligent systems blend the body's natural signals with the computational power of AI, unlocking a new era of adaptive physical intelligence. From fitness and rehabilitation to elite sports and assistive robotics, the applications are vast and growing. As we continue to merge the physical with the digital, one thing becomes clear: the smartest workouts may not come from our muscles alone—but from the machines that learn how our muscles move." },
  { type: "heading", text: "References", level: 2 },
  { type: "list", items: [
    "Alzahrani, M., & Aljaffan, N. (2024). Advanced wearable technologies for smart rehabilitation. https://example.org/alzahrani2024",
    "Tang, Z., & Liu, Y. (2025). AI-Based Movement Analysis Using Neural Networks. *Journal of Biomechanical AI*. https://example.org/tang2025ai",
    "Jadama, M., et al. (2024). AI for Personalized Health Monitoring. *HealthTech Reports*. https://example.org/jadama2024ai",
    "Zhang, X., & Patel, R. (2024). Integrating AI with Musculoskeletal Simulation. *IEEE Transactions on Biomedical Engineering*. https://example.org/zhang2024integrating",
    "Swarnakar, R., & Yadav, S. L. (2023). Artificial intelligence and machine learning in motor recovery: A rehabilitation medicine perspective. *World Journal of Clinical Cases, 11*(29), 7258–7260. https://www.wjgnet.com/2307-8960/full/v11/i29/7258.htm",
    "The Guardian. (2024). AI and football: The ethics of tracking athlete data. https://www.theguardian.com/football/2024/jan/12/ai-ethics-sports-data"
  ] },

  // Article 6: Quickstart in Robotics and Microcontrollers
  { type: "title", text: "Quickstart in Robotics and Microcontrollers: A Beginner's Journey" },
  { type: "author", text: "Md. Kaif Ibn Zaman" },
  { type: "date", text: "June 17, 2025" },
  { type: "paragraph", text: "Machines that can think, sense, and react are all around us in the modern world. Examples include voice assistants, automated lights, and even intelligent farming equipment. However, how do these enchanted tools operate? Microcontrollers and robotics hold the key to the solution. These subjects are not limited to engineers or scientists. Anyone, especially inquisitive students in school or college, can learn how to use these creative tools. Unfortunately, a lot of students experience exclusion. It’s possible that their colleges lack labs, their schools don’t have robotics clubs, and nobody in their immediate vicinity discusses creating cool devices. Dreamers who want to explore but are unsure where to start can read this article. All you need is a little direction and a glimmer of curiosity—neither a fancy lab nor a large wallet." },
  { type: "heading", text: "What Makes Robotics So Exciting?", level: 2 },
  { type: "paragraph", text: "Consider creating a tiny automobile that autonomously follows a line. Or installing lights that activate when you clap in your room. Or creating an intelligent system that irrigates plants when the soil becomes dry. Robotics includes all of these enjoyable and practical things. It’s a world where reality and imagination collide. Microcontrollers, which resemble tiny computers that can be programmed to do nearly anything, are at the core of this. ESP32 and Arduino are two well-known examples. Despite their seemingly simple appearance, they can power everything from fun games to home security systems to automatic doors." },
  { type: "image", src: "spider.jpg", caption: "" },
  { type: "heading", text: "The Real Struggle: Feeling Lost at the Start", level: 2 },
  { type: "paragraph", text: "The majority of novices fail because they feel overwhelmed or alone, not because they are stupid. Nobody in their family is a robot builder. There is no guidance provided by their school. It’s possible that they have never even handled a soldering iron. That’s totally acceptable. The goal of this journey is to start with what you have, not to have it all. Starting is crucial, regardless of whether you’re using a borrowed laptop or a used Arduino. Start clumsy. Get interested. Just get started." },
  { type: "heading", text: "Open the Door to Possibility with Simple Tools", level: 2 },
  { type: "paragraph", text: "You don’t have to purchase everything at once. A single LED light blinking is the first step in some of the most joyful projects. It’s like igniting your first spark. You can purchase a simple microcontroller, wires, a breadboard, and a few LEDs for less than 1000 BDT. That will be sufficient to realize your initial concept. How you use them matters more than the parts. You’ll gradually come to understand that these small components can assist you in producing something practical, entertaining, or significant." },
  { type: "heading", text: "The Power of Stories Over Steps", level: 2 },
  { type: "list", items: [
    "A student devises a method to remind her grandmother to take her medication.",
    "In a small rural town, a boy automates the water pump for his family.",
    "Because your professor of discrete mathematics doesn’t take attendance by hand, you want to automate your department’s attendance system."
  ] },
  { type: "paragraph", text: "These are more than just projects. These are experiences—small triumphs that add excitement and significance to learning." },
  { type: "heading", text: "You Are Not Alone: Find or Create Your Circle", level: 2 },
  { type: "paragraph", text: "Remember that there are a lot of people out there who are just like you, even if nobody in your immediate vicinity discusses robotics. Look them up on the internet. Join YouTube channels, Facebook groups, or Discord groups. Observe others make errors and correct them. Remark. Inquire. Distribute. Better yet, act as the spark. With a couple of friends, form a small group. Every weekend, get together online, at a café, or at your house. Talk about what you discovered. Arrange enjoyable builds. Not only will you develop more quickly, but you’ll also have a lot more fun along the way." },
  { type: "heading", text: "Overcoming the First Hurdles", level: 2 },
  { type: "paragraph", text: "Yes, things will go wrong. Sometimes the code won’t upload. Or the board won’t turn on. You might doubt yourself. But every expert you see today once felt the same. What matters most isn’t that you finish a project perfectly. It’s that you come back to try again the next day. That’s how real learning happens—not from tutorials, but from tiny failures turned into breakthroughs." },
  { type: "image", src: "walle.jpg", caption: "" },
  { type: "heading", text: "You Are Building More Than Projects", level: 2 },
  { type: "paragraph", text: "Your community may benefit from something that begins with a blinking light. One day, you might invent a smart farming solution, develop an inexpensive medical device, or motivate young people in your community. You’re also creating something more significant with every project: your mindset. You’re developing abilities that transcend the classroom: the ability to see issues, envision solutions, and make them a reality." },
  { type: "heading", text: "Conclusion: Start Small, Dream Big", level: 2 },
  { type: "paragraph", text: "Don’t wait for the ideal opportunity, funding, or mentor. Start with what you already have. Take lessons from your errors. Tell us about your journey. Robotics is about people like you using basic tools to solve real problems and express their creativity, not just about machines. So feel free. Tinker. Build. Fail. Give it another go. Take pride. Because creators like you are the ones who will shape the future." },
  { type: "list", items: [
    "Arduino is simple, safe, and beginner-friendly.",
    "ESP32 adds Wi-Fi and Bluetooth, so you can build smart home or IoT devices.",
    "Start with whichever you find—what matters is starting!"
  ], caption: "Curious About Arduino and ESP32?" },
  { type: "heading", text: "Final Spark", level: 2 },
  { type: "paragraph", text: "Keep a small diary, blog, or social post about each thing you try. A year from now, you’ll look back and smile at how far you’ve come." },

  // Article 7: Dopamine
  { type: "title", text: "Dopamine: The Currency of Digital Control" },
  { type: "author", text: "Md. Asif Khan" },
  { type: "date", text: "June 17, 2025" },
  { type: "paragraph", text: "If we ask a child to pick between a chocolate or a banana, what would it take? In most cases, the answer has to be chocolate. But why? Have we ever thought about it? Is it just because it feels good? Have we ever thought why we sneak into our social media every now and then? Why would we choose to lie in bed with our phone instead of studying at the table? Is it just because it feels good? While that is partially correct, it does not reveal the main reason behind these choices. Our decision-making, addiction, and behavior are all connected to the brain’s reward system, which is controlled by neurotransmitters. Among them, the most common and vital is dopamine." },
  { type: "heading", text: "What are Neurotransmitters and How Do They Function?", level: 2 },
  { type: "paragraph", text: "Neurotransmitters are chemical messengers that transmit signals between brain cells, influencing everything from mood to motivation. Four key neurotransmitters generate pleasure and reward: Dopamine creates motivation and the thrill of anticipation, like when smelling your favorite food cooking. Serotonin provides deep contentment and emotional stability, often boosted by sunlight or meaningful accomplishments. Endorphins act as natural pain relievers that also induce euphoria, such as the 'runner's high' after intense exercise. Oxytocin promotes bonding and warmth, released during hugs or moments of trust. Together, these chemicals shape life's most rewarding experiences." },
  { type: "heading", text: "The Role of Dopamine as a Neurotransmitter", level: 2 },
  { type: "paragraph", text: "Dopamine is a neurotransmitter—or brain chemical—that people sometimes call the 'feel good' hormone. That's because when we do things that trigger the release of dopamine, we feel good. In fact, we sometimes feel so good that we seek out those experiences over and over again. We discussed a child’s choice of chocolate over a banana. We said it is because it feels good. But how is dopamine related to this? Actually, when we perceive things, our brain scans every bit of information and calculates which option would give us maximum reward. But the question is, what’s a reward? A reward is anything our brain sees as good. It could be something small, like a smile or something big, like winning a trophy. Dopamine helps our brain remember rewards! Dopamine plays a big role when we make choices. It helps our brain decide if something is worth doing. It helps us weigh the rewards and the risks. Every time we think about doing something fun, risky, or new, dopamine is part of that decision. Similarly, when a child is asked to decide between chocolate and a banana, their brain analyzes the two and picks chocolate as more rewarding or more dopamine-releasing. That’s how dopamine influences our decisions." },
  { type: "heading", text: "Social Media’s UI/UX and Algorithms", level: 2 },
  { type: "paragraph", text: "In today’s digital age, social media platforms have become an integral part of our daily lives, offering instant connectivity, entertainment, and information at our fingertips. However, beneath the surface of these seemingly harmless interactions lies a complex interplay between our brain’s chemistry and the carefully designed features of social media apps. Features like likes, comments, shares, stories, and reels often compel us to stick to social media for a long time." },
  { type: "image", src: "dopamine_flowchart.png", caption: "Flowchart illustrating the dopamine loop in social media interactions." },
  { type: "paragraph", text: "Have we ever thought about why there’s no end to newsfeed scrolling or reel watching? The continuous notifications or pull-to-refresh features make us spend a long time on social media. Sometimes, we pick up our phone just because of a notification sound from social media, only to end up wasting an hour for no real reason. These platforms are designed to trigger dopamine release, creating a rewarding cycle that keeps users coming back for more. The brain’s reward system responds to likes, comments, and shares, releasing small bursts of dopamine with each interaction. This neurochemical response reinforces the behavior, making social media use habit-forming and potentially addictive. These features also cause FOMO (fear of missing out), which leads teens to get addicted to social media influence and reach." },
  { type: "image", src: "brended.png", caption: "The Dopamine Loop — A surreal visualization of a human brain connected to a smartphone, where social media interactions trigger neural responses. Glowing signals represent dopamine surges, symbolizing the addictive feedback loop and algorithmic influence of digital platforms." },
  { type: "paragraph", text: "One of the most concerning aspects is the algorithm that serves us our preferred content. Ever wondered how social media knows what your favorite content is and which contents tend to keep you long time on screen? You might discuss the 'Final Destination' movie with friends, and the next day your Instagram reels are filled with related content. Or you text a friend about needing an ESP32 microcontroller for a project, and suddenly you see ads for it everywhere. How do they know what you need? The answer is simple: we give permissions like location, voice, and camera to the social media app. Using all those permissions, they analyze our personal data along with our posts or interaction data through artificial intelligence. Then they display specific content or items. Once I stared at a person’s story for a few seconds, and then Facebook started to show that person’s posts and stories at the top of my feed. That’s how their algorithms function—to keep us on their apps for as long as possible." },
  { type: "heading", text: "Breaking the Habit", level: 2 },
  { type: "paragraph", text: "Breaking the cycle of social media addiction begins with awareness. Setting boundaries, such as limiting screen time, turning off non-essential notifications, and creating tech-free zones, can help reduce compulsive use. Practicing mindfulness, pausing to ask why you are reaching for your phone can help you regain control. Engaging in activities that naturally boost dopamine, such as exercise, creative hobbies, or spending time with friends and family can provide healthier sources of reward. Understanding how social media is designed to capture your attention empowers you to make more intentional choices about your digital habits. With conscious effort, it is possible to reclaim your time and attention from the grip of digital dopamine triggers." },
  { type: "heading", text: "References", level: 2 },
  { type: "list", items: [
    "Volkow, N. D., & Morales, M. (2015). The Brain on Drugs: From Reward to Addiction. *Neuron, 87*(4), 638–654. https://www.cell.com/neuron/pdf/S0896-6273(15)00133-6.pdf",
    "Webmedy. Dopamine and Decision Making. https://webmedy.com/blog/dopamine-decision-making/",
    "OurMental.Health. Hooked on Dopamine. https://www.ourmental.health/screen-time-sanity/hooked-on-dopamine-how-social-media-hijacks-your-brain",
    "Neurolaunch. Social Media and Dopamine. https://neurolaunch.com/social-media-dopamine/",
    "Glass Almanac. How Dopamine Influences Behavior and Decision-Making According to Science. https://glassalmanac.com/how-dopamine-influences-behavior-and-decision-making-according-to-science/",
    "Healthline. Dopamine Addiction. https://www.healthline.com/health/dopamine-addiction",
    "Verywell Mind. Can You Get Addicted to Dopamine? https://www.verywellmind.com/can-you-get-addicted-to-dopamine-5207433"
  ] },

  // Article 8: The Silent Revolution
  { type: "title", text: "The Silent Revolution" },
  { type: "author", text: "Muhaimin Kamran" },
  { type: "date", text: "June 17, 2025" },
  { type: "image", src: "brainchip.png", caption: "Visual depiction of a brain-computer interface enabling control through thought—a breakthrough achieved by Neuralink’s first human trials." },
  { type: "paragraph", text: "Once **science fictions** were dismissed as mere fantasy. In 1864, **Jules Verne** wrote *Journey to the Center of the Earth*, where he described a mission to the Moon—launched from Florida. Then, in 1870, he penned *20,000 Leagues Under the Sea*, in which **Captain Nemo** traveled beneath the ocean in an electric-powered submarine. Decades later, in 1969, **Neil Armstrong** stepped onto the Moon during the Apollo 11 mission—and science fiction began turning into reality. Today, detailed underwater exploration is routine. **Sci-fi started becoming real**." },
  { type: "paragraph", text: "In January 2024, the first successful **brain-computer interface (BCI)** was implanted—a tiny device in the brain allowing humans to interact directly with computers, AI, or prosthetics. **Noland Arbaugh**, a young man left quadriplegic after a diving accident, became the first human subject. **Neuralink** implanted a chip—called the **“Link”**—into the region of his brain that controls movement. The chip has sixty-four threads, each thinner than human hair, placed precisely by a **surgical robot**. With it, Noland can move a computer mouse using only his thoughts. He now browses the internet, plays chess, and navigates online tools without moving a single muscle. Neuralink even livestreamed him playing chess on a MacBook using only brain signals. By mid-June 2025, **BCI’s initial implementation had proven successful**. **dshufliaf**." },
  { type: "paragraph", text: "Meanwhile, AI systems, especially those developed by **OpenAI** and others—have performed remarkably well in standardized exams designed for humans. For example, AI passed all three steps of the **USMLE** (medical licensing exam), scored in the **top 10%** on the **Bar Exam**, and placed around the 90th percentile on the **LSAT** (law school admission test). It scored between 1400 and 1550 on the **SAT** and performed at around the 99th percentile in verbal reasoning and 85th percentile in quantitative reasoning on the **GRE**. On **AP exams**, AI typically scores **4s and 5s**. On top of that, it solves coding challenges across platforms like **LeetCode** and in competitive programming environments." },
  { type: "paragraph", text: "AI has also discovered **Halicin**—a novel antibiotic—by exploring chemical spaces that no human ever had. **DeepMind’s AlphaFold** predicted the 3D structure of nearly every known protein. AI can now generate full software apps, websites, scripts, even games—just from a prompt. AI tools produce short films, stunning artwork, and realistic human faces that don’t exist. **DeepMind’s AlphaStar** has beaten **99.8%** of all human *StarCraft II* players." },
  { type: "paragraph", text: "We once dreamed of the future. **Now, the future has awakened—before we were ready**." },
  { type: "paragraph", text: "In the coming years, we may see **mass adoption of BCIs**. Human thinking, analysis, and imagination could begin to merge with real-time internet data. It may even become possible for someone to **spy on our thoughts**." },
  { type: "paragraph", text: "**AI-powered robo-doctors** or **AI judges** may become mainstream—cost-effective, efficient, and widely accessible. At the same time, AI capable of exploring chemical spaces might design **deadly pathogens**. Automated law enforcement systems could operate with no empathy or human oversight. Governments may use legal AI to justify censorship or oppression. Fake videos, false news, and synthetic war footage will become harder to detect. Identities may be lost, as AI perfectly mimics faces, voices, and writing styles." },
  { type: "image", src: "aivlona.png", caption: "As AI grows more powerful, the line between empowerment and manipulation blurs. Regulation is essential to preserve identity and ethics in the age of algorithms." },
  { type: "paragraph", text: "**These technologies are advancing faster than the laws that govern them.** If left unchecked, tools designed to empower humanity could destabilize it. Regulation does not mean halting progress, it means steering it toward safe, fair outcomes." },
  { type: "paragraph", text: "**We are not yet at the point where AI thinks independently, like in science fiction.** But we are moving faster than we ever imagined. The convergence of AI, brain interfaces, and quantum computing marks a profound turning point in human history." },
  { type: "paragraph", text: "These tools carry tremendous promise—cures for diseases, universal access to knowledge, freedom from disability, and global efficiency. But without thoughtful regulation, rigorous testing, and transparent governance, they may also introduce risks for which we are not yet prepared. **We do not fear the future; we fear that it is already here**." }
]